### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ashutoshpw** [W3Dev/uptime#15]
- [ ] Remove Test Data
- [ ] Add More Sites
- [ ] Add Slack Alerts
